[mypy]
python_version = 3.13
strict = true
show_error_codes = true
explicit_package_bases = true
namespace_packages = true

[mypy-elke27_lib.*]
ignore_missing_imports = true

[mypy-pytest_homeassistant_custom_component.*]
ignore_missing_imports = true

[mypy-psutil_home_assistant.*]
ignore_missing_imports = true

[mypy-voluptuous.*]
ignore_missing_imports = true
